spring.application.name=GameStudio
spring.datasource.url=jdbc:postgresql://localhost:5432/gamestudiodb
spring.datasource.username=postgres
spring.datasource.password=12102021egorDem
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=super-secret-key-super-secret-key
jwt.access_token.expiration_time=600000
jwt.refresh_token.expiration_time=10080000
